### ISSUE TITLE
Iss-pass

### ISSUE THREAD

**Issue by CyberBitz** [kd8bxp/Simple-ISS-Notification-System#2]
The http://api.open-notify.org/iss-pass.json? Is no longer available. 

Just passing along 

Thanks,

Tom

**Comment by kd8bxp** [comment]
Thanks, I'll try to update the sketches - but it might take me a bit - busy with the holidays, and grandkids.

- LeRoy

**Comment by kd8bxp** [comment]
Ended up just removing the pass prediction code. If you (or anyone else) knows of a free api for pass predictions let me know.
Other wise, went with the least resistance option..... Thanks for letting me know. 
Hopefully this corrects the issue.

-LeRoy
